baseURL = "https://www.janraasch.com/"
languageCode = "en-US"
title = "janraasch.com"
theme="hugo-bearblog"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

disableKinds = ["taxonomy", "404", "term"]

[params]
  # Metadata for search engines and social sharing
  author = "Jan Raasch"
  description = "Jan Raasch. Hello! My name is Jan, and I am a full-stack developer passionate about creating digital products prioritizing impactful, serene, and human-centric experiences. I have been working as a professional software developer for over 12 years. Over 12 years ago, I was a mathematician. If you want to learn more about my services and how we can work together, reach out!"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Jan Raasch, full-stack developer building software for people."

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  # TODO: Generate a new "favicon.png". Maybe use 🤖.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  # TODO: Generate an up-to-date "share.png"
  images = ["images/share.png"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true
