[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.73.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.73.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Redirects and headers are GLOBAL for all builds – they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "http://lucid-leakey-72209b.netlify.com/*"
  to = "http://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from = "https://lucid-leakey-72209b.netlify.com/*"
  to = "https://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from="http://www.janraasch.de/*"
  to="http://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from="https://www.janraasch.de/*"
  to="https://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from="http://janraasch.de/*"
  to="http://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from="https://janraasch.de/*"
  to="https://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from="https://www.janraasch.com/bubble-tea-in-jena.html"
  to="https://www.janraasch.com"
  force = true
  status = 301

[[redirects]]
  from="https://www.janraasch.com/thurmensa/*"
  to="https://www.janraasch.com/:splat"
  force = true
  status = 301

[[redirects]]
  from="https://www.janraasch.com/software/"
  to="https://www.janraasch.com"
  force = true
  status = 301
